baseURL = "https://www.hrishikeshk.ml/"
disableHugoGeneratorInject = true
#disableLiveReload = true
disableKinds = ["RSS"]
enableEmoji = true
enableRobotsTXT = true
#paginate = 1
title = "Hrishikesh Kokate"
verbose = true
verboseLog = true

[markup]
  [markup.highlight]
    lineNos = true
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    pre = "house"
    url = "/"
    weight = 1

[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = false
    [minify.tdewolff.html]
      keepDefaultAttrVals = false
      keepConditionalComments = false

[outputFormats]
  [outputFormats.Manifest]
      baseName = "manifest"
      isPlainText = true
      mediaType = "application/json"
  [outputFormats.Sprites]
      baseName = "sprites"
      isPlainText = true
      mediaType = "image/svg+xml"
      path = "images"
  [outputFormats.Styles]
      baseName = "styles"
      isPlainText = true
      mediaType = "text/css"
      path = "css"
  [outputFormats.SW]
    baseName = "sw"
    isPlainText = true
    mediaType = "application/javascript"

[outputs]
  home = ["HTML", "JSON", "Manifest", "Sprites", "Styles", "SW"]

[params]
  author = "Hrishikesh Kokate"
  mainSections = ["blog", "projects"]

[server]
  [[server.headers]]
    for = "/*.vtt"
    [server.headers.values]
      Content-Type = "text/vtt"

[taxonomies]
  tag = "tags"