[build]
  publish = "public"
  command = "hugo --minify"

[build.processing]
  skip_processing = true

[build.environment]
  HUGO_ENV = "production"
  HUGO_VERSION = "0.82.1"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404